import { createFileRoute } from "@tanstack/react-router";
import { Check, MoveUpRight } from "lucide-react";
import { YearSwitcher } from "@/components/year-switcher";
import { programme2024 } from "@/lib/events";

export const Route = createFileRoute("/2024")({
  head: () => ({ meta: [
    { title: "Qiskit Fall Fest OAU 2024 | The First Signal" },
    { name: "description", content: "Revisit OAU’s inaugural Qiskit Fall Fest: a 24-day learning challenge, examination, hackathon, and final event." },
    { property: "og:title", content: "Qiskit Fall Fest OAU 2024" },
    { property: "og:description", content: "The first signal: where OAU’s quantum learning journey began." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: Page,
});

function Page() { return <div className="archive-2024"><section className="site-container py-8"><YearSwitcher current="2024" /><div className="archive-hero"><div><p className="eyebrow">Concluded · Ile-Ife</p><h1>THE FIRST<br />SIGNAL</h1></div><div className="archive-stamp">2024<br /><span>OAU</span></div><p className="max-w-md text-lg leading-8">Our inaugural edition turned twenty-four days of guided learning into examination, experimentation, and a student-built hackathon.</p></div></section><section className="bg-archive-paper py-24"><div className="site-container grid gap-16 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="eyebrow">18 October — 23 November</p><h2 className="mt-5 font-display text-5xl font-semibold">From notebooks to a final room.</h2><p className="mt-6 leading-7 text-muted-foreground">A beginner-friendly journey built around auto-graded notebooks, open-ended practice, community support, and a chance to present what participants learned.</p><div className="mt-8 space-y-3 text-sm">{["Self-paced learning", "Practical Qiskit experience", "Hackathon teamwork", "Community talks"].map(x => <p key={x} className="flex items-center gap-3"><Check className="size-4 text-archive-red" />{x}</p>)}</div></div><div className="timeline-2024">{programme2024.map(([date,title,detail],i) => <article key={title}><span className="timeline-index">0{i+1}</span><div><p className="font-mono text-xs text-archive-red">{date}</p><h3>{title}</h3><p>{detail}</p></div></article>)}</div></div></section><section className="site-container py-24"><p className="eyebrow">The record continues</p><div className="mt-5 grid gap-8 md:grid-cols-2"><h2 className="font-display text-5xl font-semibold">The 2024 gallery is being assembled.</h2><div><p className="leading-7 text-muted-foreground">We’re preserving the photographs, participant outcomes, and stories that complete this first chapter. If you took part, your record can help us tell it well.</p><a href="https://quantum-computing-club-gdg-campus-oau.github.io/qiskit-fall-fest24/" target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 font-semibold text-archive-red">Visit the original 2024 site <MoveUpRight className="size-4" /></a></div></div></section></div> }