/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R2024RouteImport } from './routes/2024'
import { Route as R2025RouteImport } from './routes/2025'
import { Route as R2026RouteImport } from './routes/2026'
import { Route as PartnershipRouteImport } from './routes/partnership'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R2024Route = R2024RouteImport.update({
  id: '/2024',
  path: '/2024',
  getParentRoute: () => rootRouteImport,
} as any)
const R2025Route = R2025RouteImport.update({
  id: '/2025',
  path: '/2025',
  getParentRoute: () => rootRouteImport,
} as any)
const R2026Route = R2026RouteImport.update({
  id: '/2026',
  path: '/2026',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2024': typeof R2024Route
  '/2025': typeof R2025Route
  '/2026': typeof R2026Route
  '/partnership': typeof PartnershipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2024': typeof R2024Route
  '/2025': typeof R2025Route
  '/2026': typeof R2026Route
  '/partnership': typeof PartnershipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2024': typeof R2024Route
  '/2025': typeof R2025Route
  '/2026': typeof R2026Route
  '/partnership': typeof PartnershipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/2024' | '/2025' | '/2026' | '/partnership'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/2024' | '/2025' | '/2026' | '/partnership'
  id: '__root__' | '/' | '/2024' | '/2025' | '/2026' | '/partnership'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2024Route: typeof R2024Route
  R2025Route: typeof R2025Route
  R2026Route: typeof R2026Route
  PartnershipRoute: typeof PartnershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2024': {
      id: '/2024'
      path: '/2024'
      fullPath: '/2024'
      preLoaderRoute: typeof R2024RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2025': {
      id: '/2025'
      path: '/2025'
      fullPath: '/2025'
      preLoaderRoute: typeof R2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2026': {
      id: '/2026'
      path: '/2026'
      fullPath: '/2026'
      preLoaderRoute: typeof R2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2024Route: R2024Route,
  R2025Route: R2025Route,
  R2026Route: R2026Route,
  PartnershipRoute: PartnershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
